from pathlib import Path

PROJECT_DIR = Path("/data4/selfsupervision/")
PROJECT_DATA_DIR = PROJECT_DIR / "chexpert"
CHEXPERT_DATA_DIR = PROJECT_DATA_DIR / "CheXpert" 
CHEXPERT_V1_DIR = CHEXPERT_DATA_DIR / "CheXpert-v1.0"

CHEXPERT_TRAIN_CSV = CHEXPERT_V1_DIR / "train.csv"
CHEXPERT_VALID_CSV = CHEXPERT_V1_DIR / "valid.csv"

CHEXPERT_TRAIN_DATA = CHEXPERT_V1_DIR / "train"
CHEXPERT_VALID_DATA = CHEXPERT_V1_DIR / "valid"