common:
  data_folder: 'data/input/15objects_lab/samples/train'
  val_folder: 'data/input/15objects_lab/samples/val'
supcon:
  batch_size: 32
  learning_rate: 0.1
  epochs: 4
  lr_decay_epochs: '2, 3'
linear:
  batch_size: 32
  learning_rate: 0.5
  epochs: 4
  lr_decay_epochs: '1, 2, 3'

  